#include "codegen.h"
#include "common.h"

static void gen_node(ASTNode *node, FILE *out) {
    if (!node) return;

    switch (node->type) {
        case AST_PROGRAM:
            for (int i = 0; i < node->program.decl_count; i++) {
                gen_node(node->program.decls[i], out);
            }
            break;

        case AST_FUNC_DECL:
            fprintf(out, "    .global %s\n", node->func.name);
            fprintf(out, "    .p2align 2\n");
            fprintf(out, "%s:\n", node->func.name);

            // Prologue
            fprintf(out, "    stp x29, x30, [sp, #-16]!\n");
            fprintf(out, "    mov x29, sp\n\n");

            // Function body
            gen_node(node->func.body, out);

            // Epilogue
            fprintf(out, "\n    ldp x29, x30, [sp], #16\n");
            fprintf(out, "    ret\n");
            break;

        case AST_STMT_RETURN:
            gen_node(node->ret_stmt.expr, out);
            break;

        case AST_EXPR_NUM:
            fprintf(out, "    mov w0, #%d\n", node->num.value);
            break;
    }
}

void generate_arm64(ASTNode *node, FILE *out) {
    fprintf(out, "// Generated by ncc (Nano C Compiler)\n");
    fprintf(out, "    .text\n");

    gen_node(node, out);
}
