#include "driver.h"
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <sys/stat.h>
#include <sys/types.h>
#include <limits.h>
#include <stdint.h>

#define FNV_PRIME 0x100000001b3ULL
#define FNV_OFFSET 0xcbf29ce484222325ULL

static uint64_t fnv1a_hash_bytes(uint64_t hash, const void *data, size_t len) {
    const unsigned char *p = (const unsigned char *)data;
    for (size_t i = 0; i < len; i++) {
        hash ^= p[i];
        hash *= FNV_PRIME;
    }
    return hash;
}

static uint64_t fnv1a_hash_str(uint64_t hash, const char *str) {
    return fnv1a_hash_bytes(hash, str, strlen(str));
}

static uint64_t hash_file_contents(uint64_t hash, const char *path) {
    FILE *fp = fopen(path, "rb");
    if (!fp) return hash;

    char buf[4096];
    size_t bytes;
    while ((bytes = fread(buf, 1, sizeof(buf), fp)) > 0) {
        hash = fnv1a_hash_bytes(hash, buf, bytes);
    }
    fclose(fp);
    return hash;
}

static bool ensure_dir_exists(const char *path) {
    struct stat st;
    if (stat(path, &st) == 0) {
        return S_ISDIR(st.st_mode);
    }
    return mkdir(path, 0755) == 0;
}

static bool create_cache_dir_recursively(const char *path) {
    char tmp[PATH_MAX];
    snprintf(tmp, sizeof(tmp), "%s", path);
    size_t len = strlen(tmp);
    if (tmp[len - 1] == '/') {
        tmp[len - 1] = '\0';
    }
    for (char *p = tmp + 1; *p; p++) {
        if (*p == '/') {
            *p = '\0';
            ensure_dir_exists(tmp);
            *p = '/';
        }
    }
    return ensure_dir_exists(tmp);
}

static bool get_cache_dir(char *buf, size_t size) {
    const char *home = getenv("HOME");
    if (home) {
        snprintf(buf, size, "%s/.cache/ncc", home);
    } else {
        snprintf(buf, size, "./.ncc_cache");
    }
    return create_cache_dir_recursively(buf);
}

static uint64_t compute_cache_key(const Options *opts, const char *compiler) {
    uint64_t hash = FNV_OFFSET;

    // Hash compiler info
    hash = fnv1a_hash_str(hash, compiler);

    // Hash compiler flags
    for (int i = 0; i < opts->flags_count; i++) {
        hash = fnv1a_hash_str(hash, opts->compiler_flags[i]);
    }

    // Hash source files metadata and contents
    for (int i = 0; i < opts->source_count; i++) {
        const char *src = opts->source_files[i];

        // If the source file is a temporary file generated by ncc,
        // we use a fixed string placeholder instead of the random path
        if (strncmp(src, "./.ncc_tmp_", 11) == 0) {
            hash = fnv1a_hash_str(hash, "__temp_source__");
        } else {
            hash = fnv1a_hash_str(hash, src);
        }

        // Hash the contents of the file
        hash = hash_file_contents(hash, src);
    }

    // Hash inline code if executing from stdin/command line
    if (opts->stdin_code) {
        hash = fnv1a_hash_str(hash, opts->stdin_code);
    }

    return hash;
}

bool find_cached_binary(const Options *opts, const char *compiler, char *cached_path_out, size_t max_len) {
    char cache_dir[PATH_MAX];
    if (!get_cache_dir(cache_dir, sizeof(cache_dir))) {
        return false;
    }

    uint64_t key = compute_cache_key(opts, compiler);
    snprintf(cached_path_out, max_len, "%s/%016llx", cache_dir, (unsigned long long)key);

    struct stat st;
    if (stat(cached_path_out, &st) == 0) {
        if (S_ISREG(st.st_mode) && (access(cached_path_out, X_OK) == 0)) {
            return true;
        }
    }
    return false;
}
